[package]
name = "kdisk"
version = "0.1.0"
authors = ["Kees van Voorthuizen <me@keesvv.nl>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sysinfo = "0.17.2"
